### ISSUE TITLE
email should be regex-validated

### ISSUE THREAD

**Issue by jameswhang** [nuvention-web/I-Front-2018#12]
I just tried putting in ```abc``` to the email field to click purchase and it moved forward. This is a bad idea because:

1. We can't contact the customers when we want to
2. It's a security risk

We should verify the email format and show alert if it's not passing the regex

**Comment by jameswhang** [comment]
Given the current UX flow it seems like we can't also match who purchased that perfume if the user doesn't provide a valid email in that form so this seems like a pretty serious issue to me.

**Comment by Mark-Jung** [comment]
아싸 개이득

**Comment by myidsan** [comment]
fixed and pushed to email-regex branch
